basic_app/urls.py
from django.urls import path, include
from basic_app import views

app_name = 'basic_app'

urlpatterns =[
    path('register', views.register, name='register'),
    path('user_login', views.user_login, name='user_login'),
] 

learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
    path('logout/$', views.user_logout,name='logout'),
    path('special/', views.special,name='special'),
]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    
    def __str__(self):
        return self.user.username

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

basic_app/views.py
from http.client import HTTPResponse
from django.shortcuts import render
from .forms import UserForm,UserProfileInfoForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request, 'basic_app/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    
    if(request.method == 'POST'):
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    
    return render(request,'basic_app/registration.html', {'user_form':user_form, 'profile_form': profile_form, 'registered':registered}) 

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            
            else:
                return HTTPResponse("ACCOUNT NOT ACTIVE")

        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password {}".format(username,password))
            return HTTPResponse("Invalid login details supplied!")

    else:
        return render(request,'basic_app/login.html', {})

templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-bav">
                <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'basic_app:register' %}">Register</a></li>

                {% if user.is_authenticated %}
                <li><a class='navbar-link' href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li><a class='navbar-link' href="{% url 'basic_app:user_login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}  
    </div>

</body>
</html>

templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Django Level Five</h1>
</div>
 
{% endblock %}

templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% load static %}

{% block body_block %}

<div class="jumbotron">

        <h1>Login Here!</h1>
        <h3>Enter your informations:</h3>

        <form action="{% url 'basic_app:user_login' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Enter Username">

            <label for="password">Password:</label>
            <input type="password" name="password" placeholder="Enter Password">

            <input type="submit" name="" value="Login">
        </form>
</div>

{% endblock %}

templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load static %}

{% block body_block %}

<div class="jumbotron">
    {% if registered %}
        <h1>Thank you for registering!</h1>
    {% else %}
        <h1>Register here!</h1>
        <h3>Fill out the form:</h3>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="" value="Register">
        </form>
    {% endif %}
</div>

{% endblock %}